swagger: "2.0"

info:
  version: 1.0.0
  title: Client API
  description: A simple CRUD service
  contact:
    email: goroshnikovanton@gmail.com
    
basePath: /api

components:
  schemas:
    Provider:
      type: object
      properties:
        _id:
          type: interger
        name:
          type: string
      example:
        _id: 1
        name: Provider

tags:
  - name: Client
    description: Client API
  - name: Provider
    description: Provider API

paths:
  /provider:
    get:
      summary: Returns providers array of objects or object if one of query parametrs provided.
      tags:
        - Provider
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/components/schemas/Provider'
        500:
          description: Database error
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Provider's name to return
        - in: query
          id: id
          required: false
          schema:
            type: string
          description: Provider's id to return
    post:
      summary: Creates a new provider in Database
      tags:
        - Provider
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Provider'
            examples:
              Provider:
                name: provider
      responses:
        200:
          description: Ok
        422:
          description: Bad Request
        500:
          description: Database error
    put:
      summary: Updates existing provider
      tags:
        - Provider
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Provider's id to update



