swagger: "2.0"

info:
  version: 1.0.0
  title: Client API
  description: A simple CRUD service
  contact:
    email: goroshnikovanton@gmail.com
    
basePath: /api

components:
  schemas:
    Provider:
      type: object
      properties:
        name:
          type: string
      example:
        name: Provider
    Client:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        providers:
          type: array
          items:
            type: string

tags:
  - name: Client
    description: Client API
  - name: Provider
    description: Provider API

paths:
  /provider:
    get:
      summary: Returns providers array of objects or object if one of query parametrs provided.
      tags:
        - Provider
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/components/schemas/Provider'
        500:
          description: Database error
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Find provider by name
    
    post:
      summary: Creates a new provider
      tags:
        - Provider
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Provider'
            examples:
              Provider:
                name: provider
      responses:
        201:
          description: Ok
        400:
          description: Bad Request
        500:
          description: Database error
    put:
      summary: Updates existing provider
      tags:
        - Provider
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/components/schemas/Provider'
        400:
          description: Bad request
        500:
          description: Database error
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Provider's id to update
    delete:
      summary: Delete existing provider
      tags:
        - Provider
      responses:
        200:
          description: Ok
        400:
          description: Bad request
        500:
          description: Database error
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Provider's id to delete
  /client:
    get:
      summary: Returns clients array of objects or object if one of query parametrs provided.
      tags:
        - Client
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/components/schemas/Client'
        500:
          description: Database error
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Find client by name
        - in: query
          email: email
          required: false
          schema:
            type: string
          description: Find client by email
        - in: query
          phone: phone
          required: false
          schema:
            type: string
          description: Find client by phone
    post:
      summary: Creates a new Client
      tags:
        - Client
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Client'
            examples:
              Client:
                name: Client
      responses:
        201:
          description: Ok
        422:
          description: Bad Request
        500:
          description: Database error
    put:
      summary: Updates existing Client
      tags:
        - Client
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/components/schemas/Client'
        400:
          description: Bad request
        500:
          description: Database error
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Id of the client to update
    delete:
      summary: Delete existing client
      tags:
        - Client
      responses:
        200:
          description: Ok
        400:
          description: Bad request
        500:
          description: Database error
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: Id of the client to delete
  /client/filter:
    get:
      summary: Returns clients with filters
      tags:
        - Client
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/components/schemas/Client'
        500:
          description: Database error
      parameters:
        - in: query
          name: name
          required: false
          schema:
            type: string
          description: Filter client by name
        - in: query
          email: email
          required: false
          schema:
            type: string
          description: Filter client by email
        - in: query
          phone: phone
          required: false
          schema:
            type: string
          description: Filter client by phone

    



